[profile.dev]
debug = 1
overflow-checks = true
incremental = true
rustflags = ["-Ctarget-cpu=native", "-Zshare-generics=y", "-Zthreads=0"]

[profile.release]
panic = "abort"
strip = true
lto = true
codegen-units = 1
overflow-checks = true
rustflags = ["-Ctarget-cpu=native"]
